title: The Waypoint
email: cornelius.soon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: # jekyllrb
github_username:  csrail

about_link: /about
contact_link: https://nz.linkedin.com/in/cornelius-soon-430597aa
github_link: https://github.com/csrail

# Build settings
markdown: kramdown
highlight: rouge

# Sass settings
sass:
    sass_dir: _sass

# Assets
odin-icon: odin.png

# External Links
link_join_the_odin_community: http://www.theodinproject.com/courses/web-development-101/lessons/join-the-odin-community
link_how_the_web_works: http://www.theodinproject.com/courses/web-development-101/lessons/how-does-the-web-work
link_git_basics: http://www.theodinproject.com/courses/web-development-101/lessons/introduction-to-git?ref=lc-pb

# Collections
collections:
  system_administration:
    output: true
  operating_systems:
    output: true